services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "Senha123"
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - ./db_data:/var/lib/mysql

  redis:
    container_name: redis-db
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

# docker-compose up -d
